# Generated by Django 6.0.5 on 2026-05-30 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_eui', models.CharField(max_length=16, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeterTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_instantaneous_flow', models.FloatField(help_text='M3/h')),
                ('forward_cumulative_flow', models.FloatField(help_text='M3')),
                ('reverse_instantaneous_flow', models.FloatField(help_text='M3/h')),
                ('reverse_cumulative_flow', models.FloatField(help_text='M3')),
                ('voltage_rtu', models.FloatField(help_text='Volts')),
                ('voltage_meter', models.FloatField(help_text='Volts')),
                ('memory_alarm', models.BooleanField(default=False)),
                ('flow_meter_alarm', models.BooleanField(default=False)),
                ('low_battery', models.BooleanField(default=False)),
                ('valve_open', models.BooleanField(default=False)),
                ('magnetic_attack', models.BooleanField(default=False)),
                ('leakage', models.BooleanField(default=False)),
                ('pipe_burst', models.BooleanField(default=False)),
                ('validity_invalid', models.BooleanField(default=False)),
                ('meter_time', models.DateTimeField(help_text='Hardware timestamp (Tp)')),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='water_meter.watermeter')),
            ],
            options={
                'verbose_name_plural': 'meter telemetry',
                'ordering': ['-meter_time'],
            },
        ),
    ]
